version: '3'
services: 
    mysql:
        image: mysql:5.7 
        container_name: mysql-01  
        volumes: 
        - .docker/mysqldata:/var/lib/mysql
        ports: 
        - 33007:3306
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel